#!/bin/bash
echo "Working hard with lots of processes and no throttling."
mkdir stats
cd code
for f in *
do 
  if [ -d "$f" ]
  then
    mkdir "../stats/$f"
    echo "Generating stats for $f"
    ../gitstats-urk/gitstats "$f" "../stats/$f" > /dev/null
  fi
done
